# Generated by Django 4.1 on 2022-09-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_difficulty_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'Difficulty'},
        ),
    ]
