# Generated by Django 4.1 on 2022-09-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='ending_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='starting_time',
        ),
    ]
