# Generated by Django 4.1 on 2022-09-23 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_rename_end_time_event_ending_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starting_time',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ending_at',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='starting_at',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
