# Generated by Django 4.1 on 2022-08-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_category_options_remove_category_friendly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
