# Generated by Django 4.1 on 2022-08-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_photo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
