# Generated by Django 4.1 on 2022-09-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_product_description_alter_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
