# Generated by Django 4.1 on 2022-09-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_tutorial_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='duration',
        ),
    ]
