# Generated by Django 4.1 on 2022-09-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_tutorial_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
