# Generated by Django 4.1 on 2022-09-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_delete_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
