# Generated by Django 4.1 on 2022-09-24 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='file',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
